version: "3"

tasks:
  setup:
    alias: s
    cmds:
      - python3 -m venv .venv
      - source .venv/bin/activate && python3 -m pip install -r requirements.txt
      - npm --prefix ./reports install
  build:
    alias: b
    cmds:
      - source .venv/bin/activate && dbt build
  test:
    alias: t
    cmds:
      - source .venv/bin/activate && dbt test
  bi:
    cmds:
      - npm --prefix ./reports run sources && npm --prefix ./reports run dev
