version: "3"

tasks:
  setup:
    aliases: [s]
    cmds:
      - python3 -m venv .venv
      - python3 -m pip install --upgrade pip
      - source .venv/bin/activate && python3 -m pip install -r requirements.txt
      - npm --prefix ./reports install

  setup-uv:
    # Requires uv https://astral.sh/uv
    aliases: [suv]
    cmds:
      - uv venv
      - source .venv/bin/activate && uv pip install -r requirements.txt
      - npm --prefix ./reports install

  build:
    aliases: [b]
    cmds:
      - source .venv/bin/activate && dbt build

  test:
    aliases: [t]
    cmds:
      - source .venv/bin/activate && dbt test

  bi:
    cmds:
      - npm --prefix ./reports run sources && npm --prefix ./reports run dev

  bbi:
    cmds:
      - task: build
      - task: bi
